// Generated by gencpp from file amr_description/elevator_service_message.msg
// DO NOT EDIT!


#ifndef AMR_DESCRIPTION_MESSAGE_ELEVATOR_SERVICE_MESSAGE_H
#define AMR_DESCRIPTION_MESSAGE_ELEVATOR_SERVICE_MESSAGE_H

#include <ros/service_traits.h>


#include <amr_description/elevator_service_messageRequest.h>
#include <amr_description/elevator_service_messageResponse.h>


namespace amr_description
{

struct elevator_service_message
{

typedef elevator_service_messageRequest Request;
typedef elevator_service_messageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct elevator_service_message
} // namespace amr_description


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::amr_description::elevator_service_message > {
  static const char* value()
  {
    return "0ac04e9a8dcf75f07af625da2a4fd966";
  }

  static const char* value(const ::amr_description::elevator_service_message&) { return value(); }
};

template<>
struct DataType< ::amr_description::elevator_service_message > {
  static const char* value()
  {
    return "amr_description/elevator_service_message";
  }

  static const char* value(const ::amr_description::elevator_service_message&) { return value(); }
};


// service_traits::MD5Sum< ::amr_description::elevator_service_messageRequest> should match
// service_traits::MD5Sum< ::amr_description::elevator_service_message >
template<>
struct MD5Sum< ::amr_description::elevator_service_messageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::amr_description::elevator_service_message >::value();
  }
  static const char* value(const ::amr_description::elevator_service_messageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::amr_description::elevator_service_messageRequest> should match
// service_traits::DataType< ::amr_description::elevator_service_message >
template<>
struct DataType< ::amr_description::elevator_service_messageRequest>
{
  static const char* value()
  {
    return DataType< ::amr_description::elevator_service_message >::value();
  }
  static const char* value(const ::amr_description::elevator_service_messageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::amr_description::elevator_service_messageResponse> should match
// service_traits::MD5Sum< ::amr_description::elevator_service_message >
template<>
struct MD5Sum< ::amr_description::elevator_service_messageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::amr_description::elevator_service_message >::value();
  }
  static const char* value(const ::amr_description::elevator_service_messageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::amr_description::elevator_service_messageResponse> should match
// service_traits::DataType< ::amr_description::elevator_service_message >
template<>
struct DataType< ::amr_description::elevator_service_messageResponse>
{
  static const char* value()
  {
    return DataType< ::amr_description::elevator_service_message >::value();
  }
  static const char* value(const ::amr_description::elevator_service_messageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AMR_DESCRIPTION_MESSAGE_ELEVATOR_SERVICE_MESSAGE_H
