// Generated by gencpp from file amr_description/elevator_service_messageResponse.msg
// DO NOT EDIT!


#ifndef AMR_DESCRIPTION_MESSAGE_ELEVATOR_SERVICE_MESSAGERESPONSE_H
#define AMR_DESCRIPTION_MESSAGE_ELEVATOR_SERVICE_MESSAGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace amr_description
{
template <class ContainerAllocator>
struct elevator_service_messageResponse_
{
  typedef elevator_service_messageResponse_<ContainerAllocator> Type;

  elevator_service_messageResponse_()
    : success(false)  {
    }
  elevator_service_messageResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::amr_description::elevator_service_messageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amr_description::elevator_service_messageResponse_<ContainerAllocator> const> ConstPtr;

}; // struct elevator_service_messageResponse_

typedef ::amr_description::elevator_service_messageResponse_<std::allocator<void> > elevator_service_messageResponse;

typedef boost::shared_ptr< ::amr_description::elevator_service_messageResponse > elevator_service_messageResponsePtr;
typedef boost::shared_ptr< ::amr_description::elevator_service_messageResponse const> elevator_service_messageResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amr_description::elevator_service_messageResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amr_description::elevator_service_messageResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::amr_description::elevator_service_messageResponse_<ContainerAllocator1> & lhs, const ::amr_description::elevator_service_messageResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::amr_description::elevator_service_messageResponse_<ContainerAllocator1> & lhs, const ::amr_description::elevator_service_messageResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace amr_description

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::amr_description::elevator_service_messageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amr_description::elevator_service_messageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amr_description::elevator_service_messageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amr_description::elevator_service_messageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amr_description::elevator_service_messageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amr_description::elevator_service_messageResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amr_description::elevator_service_messageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::amr_description::elevator_service_messageResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::amr_description::elevator_service_messageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amr_description/elevator_service_messageResponse";
  }

  static const char* value(const ::amr_description::elevator_service_messageResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amr_description::elevator_service_messageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success      # task reached\n"
"\n"
;
  }

  static const char* value(const ::amr_description::elevator_service_messageResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amr_description::elevator_service_messageResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct elevator_service_messageResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amr_description::elevator_service_messageResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amr_description::elevator_service_messageResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMR_DESCRIPTION_MESSAGE_ELEVATOR_SERVICE_MESSAGERESPONSE_H
