// Generated by gencpp from file amr_description/ElevatorServiceMessageRequest.msg
// DO NOT EDIT!


#ifndef AMR_DESCRIPTION_MESSAGE_ELEVATORSERVICEMESSAGEREQUEST_H
#define AMR_DESCRIPTION_MESSAGE_ELEVATORSERVICEMESSAGEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace amr_description
{
template <class ContainerAllocator>
struct ElevatorServiceMessageRequest_
{
  typedef ElevatorServiceMessageRequest_<ContainerAllocator> Type;

  ElevatorServiceMessageRequest_()
    : elevator()  {
    }
  ElevatorServiceMessageRequest_(const ContainerAllocator& _alloc)
    : elevator(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _elevator_type;
  _elevator_type elevator;





  typedef boost::shared_ptr< ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ElevatorServiceMessageRequest_

typedef ::amr_description::ElevatorServiceMessageRequest_<std::allocator<void> > ElevatorServiceMessageRequest;

typedef boost::shared_ptr< ::amr_description::ElevatorServiceMessageRequest > ElevatorServiceMessageRequestPtr;
typedef boost::shared_ptr< ::amr_description::ElevatorServiceMessageRequest const> ElevatorServiceMessageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator1> & lhs, const ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator2> & rhs)
{
  return lhs.elevator == rhs.elevator;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator1> & lhs, const ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace amr_description

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "134e7eb9269b8923eab3c88a53d027cb";
  }

  static const char* value(const ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x134e7eb9269b8923ULL;
  static const uint64_t static_value2 = 0xeab3c88a53d027cbULL;
};

template<class ContainerAllocator>
struct DataType< ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amr_description/ElevatorServiceMessageRequest";
  }

  static const char* value(const ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string elevator   # use \"up\" or \"down\" \n"
;
  }

  static const char* value(const ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.elevator);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ElevatorServiceMessageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amr_description::ElevatorServiceMessageRequest_<ContainerAllocator>& v)
  {
    s << indent << "elevator: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.elevator);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMR_DESCRIPTION_MESSAGE_ELEVATORSERVICEMESSAGEREQUEST_H
