// Generated by gencpp from file amr_description/ElevatorServiceMessageResponse.msg
// DO NOT EDIT!


#ifndef AMR_DESCRIPTION_MESSAGE_ELEVATORSERVICEMESSAGERESPONSE_H
#define AMR_DESCRIPTION_MESSAGE_ELEVATORSERVICEMESSAGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace amr_description
{
template <class ContainerAllocator>
struct ElevatorServiceMessageResponse_
{
  typedef ElevatorServiceMessageResponse_<ContainerAllocator> Type;

  ElevatorServiceMessageResponse_()
    : success(false)  {
    }
  ElevatorServiceMessageResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ElevatorServiceMessageResponse_

typedef ::amr_description::ElevatorServiceMessageResponse_<std::allocator<void> > ElevatorServiceMessageResponse;

typedef boost::shared_ptr< ::amr_description::ElevatorServiceMessageResponse > ElevatorServiceMessageResponsePtr;
typedef boost::shared_ptr< ::amr_description::ElevatorServiceMessageResponse const> ElevatorServiceMessageResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator1> & lhs, const ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator1> & lhs, const ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace amr_description

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amr_description/ElevatorServiceMessageResponse";
  }

  static const char* value(const ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success      # task reached\n"
"\n"
;
  }

  static const char* value(const ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ElevatorServiceMessageResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amr_description::ElevatorServiceMessageResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMR_DESCRIPTION_MESSAGE_ELEVATORSERVICEMESSAGERESPONSE_H
