// Generated by gencpp from file amr_description/ElevatorServiceMessage.msg
// DO NOT EDIT!


#ifndef AMR_DESCRIPTION_MESSAGE_ELEVATORSERVICEMESSAGE_H
#define AMR_DESCRIPTION_MESSAGE_ELEVATORSERVICEMESSAGE_H

#include <ros/service_traits.h>


#include <amr_description/ElevatorServiceMessageRequest.h>
#include <amr_description/ElevatorServiceMessageResponse.h>


namespace amr_description
{

struct ElevatorServiceMessage
{

typedef ElevatorServiceMessageRequest Request;
typedef ElevatorServiceMessageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ElevatorServiceMessage
} // namespace amr_description


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::amr_description::ElevatorServiceMessage > {
  static const char* value()
  {
    return "0ac04e9a8dcf75f07af625da2a4fd966";
  }

  static const char* value(const ::amr_description::ElevatorServiceMessage&) { return value(); }
};

template<>
struct DataType< ::amr_description::ElevatorServiceMessage > {
  static const char* value()
  {
    return "amr_description/ElevatorServiceMessage";
  }

  static const char* value(const ::amr_description::ElevatorServiceMessage&) { return value(); }
};


// service_traits::MD5Sum< ::amr_description::ElevatorServiceMessageRequest> should match
// service_traits::MD5Sum< ::amr_description::ElevatorServiceMessage >
template<>
struct MD5Sum< ::amr_description::ElevatorServiceMessageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::amr_description::ElevatorServiceMessage >::value();
  }
  static const char* value(const ::amr_description::ElevatorServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::amr_description::ElevatorServiceMessageRequest> should match
// service_traits::DataType< ::amr_description::ElevatorServiceMessage >
template<>
struct DataType< ::amr_description::ElevatorServiceMessageRequest>
{
  static const char* value()
  {
    return DataType< ::amr_description::ElevatorServiceMessage >::value();
  }
  static const char* value(const ::amr_description::ElevatorServiceMessageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::amr_description::ElevatorServiceMessageResponse> should match
// service_traits::MD5Sum< ::amr_description::ElevatorServiceMessage >
template<>
struct MD5Sum< ::amr_description::ElevatorServiceMessageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::amr_description::ElevatorServiceMessage >::value();
  }
  static const char* value(const ::amr_description::ElevatorServiceMessageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::amr_description::ElevatorServiceMessageResponse> should match
// service_traits::DataType< ::amr_description::ElevatorServiceMessage >
template<>
struct DataType< ::amr_description::ElevatorServiceMessageResponse>
{
  static const char* value()
  {
    return DataType< ::amr_description::ElevatorServiceMessage >::value();
  }
  static const char* value(const ::amr_description::ElevatorServiceMessageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AMR_DESCRIPTION_MESSAGE_ELEVATORSERVICEMESSAGE_H
