// Generated by gencpp from file amr_detection/Pose_message.msg
// DO NOT EDIT!


#ifndef AMR_DETECTION_MESSAGE_POSE_MESSAGE_H
#define AMR_DETECTION_MESSAGE_POSE_MESSAGE_H

#include <ros/service_traits.h>


#include <amr_detection/Pose_messageRequest.h>
#include <amr_detection/Pose_messageResponse.h>


namespace amr_detection
{

struct Pose_message
{

typedef Pose_messageRequest Request;
typedef Pose_messageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Pose_message
} // namespace amr_detection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::amr_detection::Pose_message > {
  static const char* value()
  {
    return "d3de3f2f8c8330f3ac521e84ce31d228";
  }

  static const char* value(const ::amr_detection::Pose_message&) { return value(); }
};

template<>
struct DataType< ::amr_detection::Pose_message > {
  static const char* value()
  {
    return "amr_detection/Pose_message";
  }

  static const char* value(const ::amr_detection::Pose_message&) { return value(); }
};


// service_traits::MD5Sum< ::amr_detection::Pose_messageRequest> should match
// service_traits::MD5Sum< ::amr_detection::Pose_message >
template<>
struct MD5Sum< ::amr_detection::Pose_messageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::amr_detection::Pose_message >::value();
  }
  static const char* value(const ::amr_detection::Pose_messageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::amr_detection::Pose_messageRequest> should match
// service_traits::DataType< ::amr_detection::Pose_message >
template<>
struct DataType< ::amr_detection::Pose_messageRequest>
{
  static const char* value()
  {
    return DataType< ::amr_detection::Pose_message >::value();
  }
  static const char* value(const ::amr_detection::Pose_messageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::amr_detection::Pose_messageResponse> should match
// service_traits::MD5Sum< ::amr_detection::Pose_message >
template<>
struct MD5Sum< ::amr_detection::Pose_messageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::amr_detection::Pose_message >::value();
  }
  static const char* value(const ::amr_detection::Pose_messageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::amr_detection::Pose_messageResponse> should match
// service_traits::DataType< ::amr_detection::Pose_message >
template<>
struct DataType< ::amr_detection::Pose_messageResponse>
{
  static const char* value()
  {
    return DataType< ::amr_detection::Pose_message >::value();
  }
  static const char* value(const ::amr_detection::Pose_messageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AMR_DETECTION_MESSAGE_POSE_MESSAGE_H
