// Generated by gencpp from file amr_detection/pose_messageRequest.msg
// DO NOT EDIT!


#ifndef AMR_DETECTION_MESSAGE_POSE_MESSAGEREQUEST_H
#define AMR_DETECTION_MESSAGE_POSE_MESSAGEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace amr_detection
{
template <class ContainerAllocator>
struct pose_messageRequest_
{
  typedef pose_messageRequest_<ContainerAllocator> Type;

  pose_messageRequest_()
    {
    }
  pose_messageRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::amr_detection::pose_messageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amr_detection::pose_messageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct pose_messageRequest_

typedef ::amr_detection::pose_messageRequest_<std::allocator<void> > pose_messageRequest;

typedef boost::shared_ptr< ::amr_detection::pose_messageRequest > pose_messageRequestPtr;
typedef boost::shared_ptr< ::amr_detection::pose_messageRequest const> pose_messageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amr_detection::pose_messageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amr_detection::pose_messageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace amr_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::amr_detection::pose_messageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amr_detection::pose_messageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amr_detection::pose_messageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amr_detection::pose_messageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amr_detection::pose_messageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amr_detection::pose_messageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amr_detection::pose_messageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::amr_detection::pose_messageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::amr_detection::pose_messageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amr_detection/pose_messageRequest";
  }

  static const char* value(const ::amr_detection::pose_messageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amr_detection::pose_messageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::amr_detection::pose_messageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amr_detection::pose_messageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose_messageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amr_detection::pose_messageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::amr_detection::pose_messageRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // AMR_DETECTION_MESSAGE_POSE_MESSAGEREQUEST_H
