(cl:defpackage amr_description-srv
  (:use )
  (:export
   "ELEVATORSERVICEMESSAGE"
   "<ELEVATORSERVICEMESSAGE-REQUEST>"
   "ELEVATORSERVICEMESSAGE-REQUEST"
   "<ELEVATORSERVICEMESSAGE-RESPONSE>"
   "ELEVATORSERVICEMESSAGE-RESPONSE"
  ))

