// Generated by gencpp from file amr_localization/Poi_message.msg
// DO NOT EDIT!


#ifndef AMR_LOCALIZATION_MESSAGE_POI_MESSAGE_H
#define AMR_LOCALIZATION_MESSAGE_POI_MESSAGE_H

#include <ros/service_traits.h>


#include <amr_localization/Poi_messageRequest.h>
#include <amr_localization/Poi_messageResponse.h>


namespace amr_localization
{

struct Poi_message
{

typedef Poi_messageRequest Request;
typedef Poi_messageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Poi_message
} // namespace amr_localization


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::amr_localization::Poi_message > {
  static const char* value()
  {
    return "ebb8801b9a503fdd5d709f43edb7318f";
  }

  static const char* value(const ::amr_localization::Poi_message&) { return value(); }
};

template<>
struct DataType< ::amr_localization::Poi_message > {
  static const char* value()
  {
    return "amr_localization/Poi_message";
  }

  static const char* value(const ::amr_localization::Poi_message&) { return value(); }
};


// service_traits::MD5Sum< ::amr_localization::Poi_messageRequest> should match
// service_traits::MD5Sum< ::amr_localization::Poi_message >
template<>
struct MD5Sum< ::amr_localization::Poi_messageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::amr_localization::Poi_message >::value();
  }
  static const char* value(const ::amr_localization::Poi_messageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::amr_localization::Poi_messageRequest> should match
// service_traits::DataType< ::amr_localization::Poi_message >
template<>
struct DataType< ::amr_localization::Poi_messageRequest>
{
  static const char* value()
  {
    return DataType< ::amr_localization::Poi_message >::value();
  }
  static const char* value(const ::amr_localization::Poi_messageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::amr_localization::Poi_messageResponse> should match
// service_traits::MD5Sum< ::amr_localization::Poi_message >
template<>
struct MD5Sum< ::amr_localization::Poi_messageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::amr_localization::Poi_message >::value();
  }
  static const char* value(const ::amr_localization::Poi_messageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::amr_localization::Poi_messageResponse> should match
// service_traits::DataType< ::amr_localization::Poi_message >
template<>
struct DataType< ::amr_localization::Poi_messageResponse>
{
  static const char* value()
  {
    return DataType< ::amr_localization::Poi_message >::value();
  }
  static const char* value(const ::amr_localization::Poi_messageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AMR_LOCALIZATION_MESSAGE_POI_MESSAGE_H
