// Generated by gencpp from file amr_localization/Poi_messageRequest.msg
// DO NOT EDIT!


#ifndef AMR_LOCALIZATION_MESSAGE_POI_MESSAGEREQUEST_H
#define AMR_LOCALIZATION_MESSAGE_POI_MESSAGEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace amr_localization
{
template <class ContainerAllocator>
struct Poi_messageRequest_
{
  typedef Poi_messageRequest_<ContainerAllocator> Type;

  Poi_messageRequest_()
    : label()  {
    }
  Poi_messageRequest_(const ContainerAllocator& _alloc)
    : label(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _label_type;
  _label_type label;





  typedef boost::shared_ptr< ::amr_localization::Poi_messageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amr_localization::Poi_messageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Poi_messageRequest_

typedef ::amr_localization::Poi_messageRequest_<std::allocator<void> > Poi_messageRequest;

typedef boost::shared_ptr< ::amr_localization::Poi_messageRequest > Poi_messageRequestPtr;
typedef boost::shared_ptr< ::amr_localization::Poi_messageRequest const> Poi_messageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amr_localization::Poi_messageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amr_localization::Poi_messageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::amr_localization::Poi_messageRequest_<ContainerAllocator1> & lhs, const ::amr_localization::Poi_messageRequest_<ContainerAllocator2> & rhs)
{
  return lhs.label == rhs.label;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::amr_localization::Poi_messageRequest_<ContainerAllocator1> & lhs, const ::amr_localization::Poi_messageRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace amr_localization

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::amr_localization::Poi_messageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amr_localization::Poi_messageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amr_localization::Poi_messageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amr_localization::Poi_messageRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amr_localization::Poi_messageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amr_localization::Poi_messageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amr_localization::Poi_messageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea23f97416b04c6151d2b576c0665ac1";
  }

  static const char* value(const ::amr_localization::Poi_messageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea23f97416b04c61ULL;
  static const uint64_t static_value2 = 0x51d2b576c0665ac1ULL;
};

template<class ContainerAllocator>
struct DataType< ::amr_localization::Poi_messageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amr_localization/Poi_messageRequest";
  }

  static const char* value(const ::amr_localization::Poi_messageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amr_localization::Poi_messageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string label # may be the label of the position or the \"end\" command to save the pose\n"
;
  }

  static const char* value(const ::amr_localization::Poi_messageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amr_localization::Poi_messageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Poi_messageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amr_localization::Poi_messageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amr_localization::Poi_messageRequest_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.label);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMR_LOCALIZATION_MESSAGE_POI_MESSAGEREQUEST_H
