// Generated by gencpp from file amr_localization/Poi_messageResponse.msg
// DO NOT EDIT!


#ifndef AMR_LOCALIZATION_MESSAGE_POI_MESSAGERESPONSE_H
#define AMR_LOCALIZATION_MESSAGE_POI_MESSAGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace amr_localization
{
template <class ContainerAllocator>
struct Poi_messageResponse_
{
  typedef Poi_messageResponse_<ContainerAllocator> Type;

  Poi_messageResponse_()
    : output()  {
    }
  Poi_messageResponse_(const ContainerAllocator& _alloc)
    : output(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::amr_localization::Poi_messageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amr_localization::Poi_messageResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Poi_messageResponse_

typedef ::amr_localization::Poi_messageResponse_<std::allocator<void> > Poi_messageResponse;

typedef boost::shared_ptr< ::amr_localization::Poi_messageResponse > Poi_messageResponsePtr;
typedef boost::shared_ptr< ::amr_localization::Poi_messageResponse const> Poi_messageResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amr_localization::Poi_messageResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amr_localization::Poi_messageResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::amr_localization::Poi_messageResponse_<ContainerAllocator1> & lhs, const ::amr_localization::Poi_messageResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::amr_localization::Poi_messageResponse_<ContainerAllocator1> & lhs, const ::amr_localization::Poi_messageResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace amr_localization

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::amr_localization::Poi_messageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amr_localization::Poi_messageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amr_localization::Poi_messageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amr_localization::Poi_messageResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amr_localization::Poi_messageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amr_localization::Poi_messageResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amr_localization::Poi_messageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0825d95fdfa2c8f4bbb4e9c74bccd3fd";
  }

  static const char* value(const ::amr_localization::Poi_messageResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0825d95fdfa2c8f4ULL;
  static const uint64_t static_value2 = 0xbbb4e9c74bccd3fdULL;
};

template<class ContainerAllocator>
struct DataType< ::amr_localization::Poi_messageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amr_localization/Poi_messageResponse";
  }

  static const char* value(const ::amr_localization::Poi_messageResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amr_localization::Poi_messageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string output # indicate the file poi.yaml saved\n"
;
  }

  static const char* value(const ::amr_localization::Poi_messageResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amr_localization::Poi_messageResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Poi_messageResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amr_localization::Poi_messageResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amr_localization::Poi_messageResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMR_LOCALIZATION_MESSAGE_POI_MESSAGERESPONSE_H
