amr_crick:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # 1/Position Controllers ---------------------------------------
    roll_1_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: roll_1_joint
      pid: {p: 11, i: 0.0, d: 0}
    # To add more just add them here as the first one

    # 2/Position Controllers ---------------------------------------
    roll_2_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: roll_2_joint
      pid: {p: 11, i: 0.0, d: 0}
    # To add more just add them here as the first one

    # 3/Position Controllers ---------------------------------------
    roll_3_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: roll_3_joint
      pid: {p: 11, i: 0.0, d: 0}
    # To add more just add them here as the first one
   
    # 4/Position Controllers ---------------------------------------
    roll_4_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: roll_4_joint
      pid: {p: 11, i: 0.0, d: 0}
    # To add more just add them here as the first one
    
    # 5/Position Controllers ---------------------------------------
    roll_5_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: roll_5_joint
      pid: {p: 11, i: 0.0, d: 0}
    # To add more just add them here as the first one

    # 6/Position Controllers ---------------------------------------
    roll_6_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: roll_6_joint
      pid: {p: 11, i: 0.0, d: 0}
    # To add more just add them here as the first one
    
    # 7/Position Controllers ---------------------------------------
    roll_7_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: roll_7_joint
      pid: {p: 11, i: 0.0, d: 0}
    # To add more just add them here as the first one